steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/training-384005/api-poc:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/training-384005/api-poc:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/training-384005/api-poc:${SHORT_SHA}'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/training-384005/api-poc:latest'
    env:
      - 'CLOUD_BUILD_TAG=gcr.io/training-384005/api-poc:latest'
  - name: google/cloud-sdk
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'my-service'
      - '--image=gcr.io/training-384005/api-poc:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
