steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${_GCP_PROJECT}/${_DOCKER_IMAGE}:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${_GCP_PROJECT}/${_DOCKER_IMAGE}:latest'
      - '.'
  # Additional build steps can be added here
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${_GCP_PROJECT}/${_DOCKER_IMAGE}:${SHORT_SHA}'
  # Additional push steps can be added here
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${_GCP_PROJECT}/${_DOCKER_IMAGE}:latest'
    env:
      - 'CLOUD_BUILD_TAG=gcr.io/${_GCP_PROJECT}/${_DOCKER_IMAGE}:latest'
  # Additional push steps can be added here
  
  - name: gcr.io/cloud-builders/kubectl
    args:
      - 'apply'
      - '-f'
      - 'deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_CUSTOM_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CUSTOM_CLUSTER}'
  # Additional deployment steps can be added here
  
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - 'run'
      - '--filename=deployment.yaml'
      - '--image=gcr.io/${_GCP_PROJECT}/${_DOCKER_IMAGE}:latest'
      - '--location=${_CUSTOM_REGION}'
      - '--cluster=${_CUSTOM_CLUSTER}'
  # Additional deployment steps can be added here

timeout: 1200s
substitutions:
  _GCP_PROJECT: training-384005
  _CUSTOM_REGION: us-central1-a
  _CUSTOM_CLUSTER: my-cluster
  _DOCKER_IMAGE: api-poc
  _DEPLOYMENT_NAME: my-cluster
  _REPLICAS: '1'
  _CONTAINER_PORT1: '5000'
  _CONTAINER_PORT2: '8000'
  _SERVICE_NAME: my-cluster
  _SERVICE_PORT1: '80'
  _SERVICE_PORT2: '8000'
  _SERVICE_TYPE: LoadBalancer
