apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cluster
  labels:
    app: my-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-cluster
  template:
    metadata:
      labels:
        app: my-cluster
    spec:
      containers:
      - name: cluster1
        image: gcr.io/training-384005/api-poc:latest
        ports:
        - containerPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: my-cluster
spec:
  selector:
    app: my-cluster
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer