apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cluster1
  labels:
    app: api-cluster1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cluster1
  template:
    metadata:
      labels:
        app: api-cluster1
    spec:
      containers:
      - name: cluster1
        image: gcr.io/training-384005/api-poc
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: api-cluster1
spec:
  selector:
    app: api-cluster1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer