apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-cluster-training
  labels:
    app: gke-cluster-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-cluster-training
  template:
    metadata:
      labels:
        app: gke-cluster-training
    spec:
      containers:
      - name: gke-cluster-training-container
        image: gcr.io/tatami-devops/api-poc:latest
        ports:
        - containerPort: 5000

---
kind: Service
apiVersion: v1
metadata:
  name: gke-cluster-training-service
spec:
  selector:
    app: gke-cluster-training-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gke-cluster-training-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gke-cluster-training-service
            port:
              number: 80
