apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster1
  labels:
    app: cluster1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster1
  template:
    metadata:
      labels:
        app: cluster1
    spec:
      containers:
      - name: cluster1
        image: us.gcr.io/admin-352301/flaskdemoimage
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: cluster1
spec:
  selector:
    app: cluster1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer