apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ env "DEPLOYMENT_NAME" }}
  labels:
    app: {{ env "DEPLOYMENT_NAME" }}
spec:
  replicas: {{ env "REPLICAS" }}
  selector:
    matchLabels:
      app: {{ env "DEPLOYMENT_NAME" }}
  template:
    metadata:
      labels:
        app: {{ env "DEPLOYMENT_NAME" }}
    spec:
      containers:
      - name: cluster1
        image: gcr.io/{{ env "PROJECT_ID" }}/{{ env "DOCKER_IMAGE" }}:latest
        ports:
        - containerPort: {{ env "CONTAINER_PORT1" }}
        - containerPort: {{ env "CONTAINER_PORT2" }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ env "SERVICE_NAME" }}
spec:
  selector:
    app: {{ env "SERVICE_NAME" }}
  ports:
  - name: http
    protocol: TCP
    port: {{ env "SERVICE_PORT1" }}
    targetPort: {{ env "CONTAINER_PORT1" }}
  - name: metrics
    protocol: TCP
    port: {{ env "SERVICE_PORT2" }}
    targetPort: {{ env "CONTAINER_PORT2" }}
  type: {{ env "SERVICE_TYPE" }}
